[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
writemind = "GqN1sq6Y38DXgwHd2tZVGaBEyjUsphu48W4gt6BeXu7S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bheet/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[target.typescript]
out_dir = "target/types"
